src/HomeAutio.Mqtt.GoogleHome/Models/GoogleHomeGraph/Devices.cs
using System.Collections.Generic;
using Newtonsoft.Json;

namespace HomeAutio.Mqtt.GoogleHome.Models.GoogleHomeGraph
{
    /// <summary>
    /// Devices request object.
    /// </summary>
    public class Devices
    {
        /// <summary>
        /// States.
        /// </summary>
        [JsonProperty(ItemConverterType = typeof(ObjectDictionaryConverter))]
        public IDictionary<string, IDictionary<string, object>> States { get; set; }
    }
}

src/HomeAutio.Mqtt.GoogleHome/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using HomeAutio.Mqtt.GoogleHome.ActionFilters;
using HomeAutio.Mqtt.GoogleHome.Models;
using HomeAutio.Mqtt.GoogleHome.Models.State;
using HomeAutio.Mqtt.GoogleHome.Validation;
using HomeAutio.Mqtt.GoogleHome.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace HomeAutio.Mqtt.GoogleHome.Controllers
{
    /// <summary>
    /// Devices controller.
    /// </summary>
    [Authorize]
    public class DevicesController : Controller
    {
        private readonly ILogger<DevicesController> _log;

        private readonly GoogleDeviceRepository _deviceRepository;

        /// <summary>
        /// Initializes a new instance of the <see cref="DevicesController"/> class.
        /// </summary>
        /// <param name="logger">Logging instance.</param>
        /// <param name="deviceRepository">Device repository.</param>
        public DevicesController(
            ILogger<DevicesController> logger,
            GoogleDeviceRepository deviceRepository)
        {
            _log = logger ?? throw new ArgumentException(nameof(logger));
            _deviceRepository = deviceRepository ?? throw new ArgumentException(nameof(deviceRepository));
        }

        /// <summary>
        /// Index.
        /// </summary>
        /// <returns>Response.</returns>
        public IActionResult Index()
        {
            var model = _deviceRepository.GetAll()
                .OrderBy(device => device.Id)
                .ToList();

            return View(model);
        }

        /// <summary>
        /// Create device.
        /// </summary>
        /// <returns>Response.</returns>
        [ImportModelState]
        public IActionResult Create()
        {
            var model = new DeviceViewModel();

            return View(model);
        }

        /// <summary>
        /// Create device.
        /// </summary>
        /// <param name="viewModel">View Model.</param>
        /// <returns>Response.</returns>
        [HttpPost]
        [ExportModelState]
        public IActionResult Create(DeviceViewModel viewModel)
        {
            if (_deviceRepository.Contains(viewModel.Id))
                ModelState.AddModelError("Id", "Device Id already exists");

            // Set new values
            var device = new Device
            {
                Id = viewModel.Id,
                Type = viewModel.Type,
                Disabled = viewModel.Disabled,
                WillReportState = viewModel.WillReportState,
                RoomHint = viewModel.RoomHint,
                Name = new NameInfo
                {
                    Name = viewModel.Name
                },
                Traits = new List<DeviceTrait>()
            };

            // Default names
            if (!string.IsNullOrEmpty(viewModel.DefaultNames))
                device.Name.DefaultNames = viewModel.DefaultNames.Split(',').Select(x => x.Trim()).ToList();
            else
                device.Name.DefaultNames = new List<string>();

            // Nicknames
            if (!string.IsNullOrEmpty(viewModel.Nicknames))
                device.Name.Nicknames = viewModel.Nicknames.Split(',').Select(x => x.Trim()).ToList();
            else
                device.Name.Nicknames = new List<string>();

            // Device Info
            if (!string.IsNullOrEmpty(viewModel.Manufacturer) ||
                !string.IsNullOrEmpty(viewModel.Model) ||
                !string.IsNullOrEmpty(viewModel.HwVersion) ||
                !string.IsNullOrEmpty(viewModel.SwVersion))
            {
                if (device.DeviceInfo == null)
                    device.DeviceInfo = new DeviceInfo();

                device.DeviceInfo.Manufacturer = !string.IsNullOrEmpty(viewModel.Manufacturer) ? viewModel.Manufacturer : null;
                device.DeviceInfo.Model = !string.IsNullOrEmpty(viewModel.Model) ? viewModel.Model : null;
                device.DeviceInfo.HwVersion = !string.IsNullOrEmpty(viewModel.HwVersion) ? viewModel.HwVersion : null;
                device.DeviceInfo.SwVersion = !string.IsNullOrEmpty(viewModel.SwVersion) ? viewModel.SwVersion : null;
            }
            else
            {
                device.DeviceInfo = null;
            }

            // Final validation
            foreach (var error in DeviceValidator.Validate(device))
                ModelState.AddModelError(string.Empty, error);

            if (!ModelState.IsValid)
                return RedirectToAction("Create");

            // Save changes
            _deviceRepository.Add(device);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Delete device.
        /// </summary>
        /// <param name="deviceId">Device id.</param>
        /// <returns>Response.</returns>
        [HttpPost]
        public IActionResult Delete([Required] string deviceId)
        {
            if (!_deviceRepository.Contains(deviceId))
                return NotFound();

            // Save changes
            _deviceRepository.Delete(deviceId);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Edit device.
        /// </summary>
        /// <param name="deviceId">Device id.</param>
        /// <returns>Response.</returns>
        [ImportModelState]
        public IActionResult Edit([Required] string deviceId)
        {
            if (!_deviceRepository.Contains(deviceId))
                return NotFound();

            var device = _deviceRepository.Get(deviceId);
            var model = new DeviceViewModel
            {
                Id = device.Id,
                Type = device.Type,
                Disabled = device.Disabled,
                WillReportState = device.WillReportState,
                RoomHint = device.RoomHint,
                Name = device.Name.Name,
                DefaultNames = string.Join(',', device.Name.DefaultNames),
                Nicknames = string.Join(',', device.Name.Nicknames),
            };

            if (device.DeviceInfo != null)
            {
                model.Manufacturer = device.DeviceInfo.Manufacturer;
                model.Model = device.DeviceInfo.Model;
                model.HwVersion = device.DeviceInfo.HwVersion;
                model.SwVersion = device.DeviceInfo.SwVersion;
            }

            if (device.Traits != null)
            {
                model.Traits = device.Traits.Select(x => x.Trait).OrderBy(trait => trait);
            }
            else
            {
                model.Traits = new List<TraitType>();
            }

            return View(model);
        }

        /// <summary>
        /// Edit device.
        /// </summary>
        /// <param name="deviceId">Device id.</param>
        /// <param name="viewModel">View Model.</param>
        /// <returns>Response.</returns>
        [HttpPost]
        [ExportModelState]
        public IActionResult Edit([Required] string deviceId, DeviceViewModel viewModel)
        {
            if (!_deviceRepository.Contains(deviceId))
                return NotFound();

            // Set new values
            var device = _deviceRepository.GetDetached(deviceId);
            device.Id = viewModel.Id;
            device.Type = viewModel.Type;
            device.Disabled = viewModel.Disabled;
            device.WillReportState = viewModel.WillReportState;
            device.RoomHint = viewModel.RoomHint;
            device.Name.Name = viewModel.Name;

            // Default names
            if (!string.IsNullOrEmpty(viewModel.DefaultNames))
                device.Name.DefaultNames = viewModel.DefaultNames.Split(',').Select(x => x.Trim()).ToList();
            else
                device.Name.DefaultNames = new List<string>();

            // Nicknames
            if (!string.IsNullOrEmpty(viewModel.Nicknames))
                device.Name.Nicknames = viewModel.Nicknames.Split(',').Select(x => x.Trim()).ToList();
            else
                device.Name.Nicknames = new List<string>();

            // Device Info
            if (!string.IsNullOrEmpty(viewModel.Manufacturer) ||
                !string.IsNullOrEmpty(viewModel.Model) ||
                !string.IsNullOrEmpty(viewModel.HwVersion) ||
                !string.IsNullOrEmpty(viewModel.SwVersion))
            {
                if (device.DeviceInfo == null)
                    device.DeviceInfo = new DeviceInfo();

                device.DeviceInfo.Manufacturer = !string.IsNullOrEmpty(viewModel.Manufacturer) ? viewModel.Manufacturer : null;
                device.DeviceInfo.Model = !string.IsNullOrEmpty(viewModel.Model) ? viewModel.Model : null;
                device.DeviceInfo.HwVersion = !string.IsNullOrEmpty(viewModel.HwVersion) ? viewModel.HwVersion : null;
                device.DeviceInfo.SwVersion = !string.IsNullOrEmpty(viewModel.SwVersion) ? viewModel.SwVersion : null;
            }
            else
            {
                device.DeviceInfo = null;
            }

            // Final validation
            foreach (var error in DeviceValidator.Validate(device))
                ModelState.AddModelError(string.Empty, error);

            if (!ModelState.IsValid)
                return RedirectToAction("Edit", new { deviceId });

            // Save changes
            _deviceRepository.Update(deviceId, device);

            return RedirectToAction("Index");
        }
    }
}

src/HomeAutio.Mqtt.GoogleHome/Controllers/TraitsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using HomeAutio.Mqtt.GoogleHome.ActionFilters;
using HomeAutio.Mqtt.GoogleHome.Models;
using HomeAutio.Mqtt.GoogleHome.Models.State;
using HomeAutio.Mqtt.GoogleHome.Validation;
using HomeAutio.Mqtt.GoogleHome.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace HomeAutio.Mqtt.GoogleHome.Controllers
{
    /// <summary>
    /// Traits controller.
    /// </summary>
    [Authorize]
    public class TraitsController : Controller
    {
        private readonly ILogger<TraitsController> _log;

        private readonly GoogleDeviceRepository _deviceRepository;

        /// <summary>
        /// Initializes a new instance of the <see cref="TraitsController"/> class.
        /// </summary>
        /// <param name="logger">Logging instance.</param>
        /// <param name="deviceRepository">Device repository.</param>
        public TraitsController(
            ILogger<TraitsController> logger,
            GoogleDeviceRepository deviceRepository)
        {
            _log = logger ?? throw new ArgumentException(nameof(logger));
            _deviceRepository = deviceRepository ?? throw new ArgumentException(nameof(deviceRepository));
        }

        /// <summary>
        /// Edit device.
        /// </summary>
        /// <param name="deviceId">Device id.</param>
        /// <returns>Response.</returns>
        [ImportModelState]
        public IActionResult Create([Required] string deviceId)
        {
            if (!_deviceRepository.Contains(deviceId))
                return NotFound();

            var model = new TraitViewModel();

            return View(model);
        }

        /// <summary>
        /// Edit trait.
        /// </summary>
        /// <param name="deviceId">Device id.</param>
        /// <param name="viewModel">View Model.</param>
        /// <returns>Response.</returns>
        [HttpPost]
        [ExportModelState]
        public IActionResult Create([Required] string deviceId, TraitViewModel viewModel)
        {
            if (!_deviceRepository.Contains(deviceId))
                return NotFound();

            var device = _deviceRepository.GetDetached(deviceId);
            if (device.Traits.Any(x => x.Trait == viewModel.Trait))
                ModelState.AddModelError("Trait", "Device already contains trait");

            // Set values
            var trait = new DeviceTrait
            {
                Trait = viewModel.Trait,
                Attributes = !string.IsNullOrEmpty(viewModel.Attributes) ? JsonConvert.DeserializeObject<Dictionary<string, object>>(viewModel.Attributes, new ObjectDictionaryConverter()) : null,
                Commands = !string.IsNullOrEmpty(viewModel.Commands) ? JsonConvert.DeserializeObject<Dictionary<string, IDictionary<string, string>>>(viewModel.Commands) : null,
                State = !string.IsNullOrEmpty(viewModel.State) ? JsonConvert.DeserializeObject<Dictionary<string, DeviceState>>(viewModel.State) : null
            };

            // Final validation
            foreach (var error in DeviceTraitValidator.Validate(trait))
                ModelState.AddModelError(string.Empty, error);

            if (!ModelState.IsValid)
                return RedirectToAction("Create", new { deviceId });

            // Save changes
            device.Traits.Add(trait);
            _deviceRepository.Update(deviceId, device);

            return RedirectToAction("Edit", "Devices", new { deviceId });
        }

        /// <summary>
        /// Delete device.
        /// </summary>
        /// <param name="deviceId">Device id.</param>
        /// <param name="traitId">Trait id.</param>
        /// <returns>Response.</returns>
        [HttpPost]
        public IActionResult Delete([Required] string deviceId, [Required] string traitId)
        {
            if (!_deviceRepository.Contains(deviceId))
                return NotFound();

            var device = _deviceRepository.GetDetached(deviceId);

            var traitEnumId = traitId.ToEnum<TraitType>();
            if (!device.Traits.Any(x => x.Trait == traitEnumId))
                return NotFound();

            // Save changes
            device.Traits.Remove(device.Traits.First(x => x.Trait == traitEnumId));
            _deviceRepository.Update(deviceId, device);

            return RedirectToAction("Edit", "Devices", new { deviceId });
        }

        /// <summary>
        /// Edit device.
        /// </summary>
        /// <param name="deviceId">Device id.</param>
        /// <param name="traitId">Trait id.</param>
        /// <returns>Response.</returns>
        [ImportModelState]
        public IActionResult Edit([Required] string deviceId, [Required] string traitId)
        {
            if (!_deviceRepository.Contains(deviceId))
                return NotFound();

            var device = _deviceRepository.Get(deviceId);

            var traitEnumId = traitId.ToEnum<TraitType>();
            if (!device.Traits.Any(x => x.Trait == traitEnumId))
                return NotFound();

            // Get trait
            var trait = device.Traits.First(x => x.Trait == traitEnumId);
            var model = new TraitViewModel
            {
                Trait = trait.Trait,
                Attributes = trait.Attributes != null ? JsonConvert.SerializeObject(trait.Attributes, Formatting.Indented) : null,
                Commands = trait.Commands != null ? JsonConvert.SerializeObject(trait.Commands, Formatting.Indented) : null,
                State = trait.State != null ? JsonConvert.SerializeObject(trait.State, Formatting.Indented) : null
            };

            return View(model);
        }

        /// <summary>
        /// Edit trait.
        /// </summary>
        /// <param name="deviceId">Device id.</param>
        /// <param name="traitId">Trait id.</param>
        /// <param name="viewModel">View Model.</param>
        /// <returns>Response.</returns>
        [HttpPost]
        [ExportModelState]
        public IActionResult Edit([Required] string deviceId, [Required] string traitId, TraitViewModel viewModel)
        {
            if (!_deviceRepository.Contains(deviceId))
                return NotFound();

            var device = _deviceRepository.GetDetached(deviceId);

            var traitEnumId = traitId.ToEnum<TraitType>();
            if (!device.Traits.Any(x => x.Trait == traitEnumId))
                return NotFound();

            // Lock the trait type just in case
            viewModel.Trait = traitEnumId;

            // Set new values
            var trait = device.Traits.FirstOrDefault(x => x.Trait == traitEnumId);
            trait.Attributes = !string.IsNullOrEmpty(viewModel.Attributes) ? JsonConvert.DeserializeObject<Dictionary<string, object>>(viewModel.Attributes, new ObjectDictionaryConverter()) : null;
            trait.Commands = !string.IsNullOrEmpty(viewModel.Commands) ? JsonConvert.DeserializeObject<Dictionary<string, IDictionary<string, string>>>(viewModel.Commands) : null;
            trait.State = !string.IsNullOrEmpty(viewModel.State) ? JsonConvert.DeserializeObject<Dictionary<string, DeviceState>>(viewModel.State) : null;

            // Final validation
            foreach (var error in DeviceTraitValidator.Validate(trait))
                ModelState.AddModelError(string.Empty, error);

            if (!ModelState.IsValid)
                return RedirectToAction("Edit", new { deviceId, traitId });

            // Save changes
            _deviceRepository.Update(deviceId, device);

            return RedirectToAction("Edit", "Devices", new { deviceId });
        }
    }
}

src/HomeAutio.Mqtt.GoogleHome/Views/Devices/Create.cshtml
@model HomeAutio.Mqtt.GoogleHome.ViewModels.DeviceViewModel

@section Scripts {
    <script>
        var openDocumentation = function () {
            var deviceTypeDropDown = document.getElementById("Type");
            var deviceType = deviceTypeDropDown.options[deviceTypeDropDown.selectedIndex].text;

            if (deviceType !== "Please select") {
                window.open('https://developers.google.com/actions/smarthome/guides/' + deviceType.toLowerCase());
            }
        }
    </script>
}

<div class="device-page">
    <div class="page-header">
        <h1>Create Device</h1>
    </div>

    <partial name="_ValidationSummary" />

    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Device</h3>
                </div>
                <form method="post">
                    <div class="panel-body">
                        <fieldset>
                            <div class="form-group">
                                <label asp-for="Id">Device Id</label>
                                <input class="form-control" placeholder="Device Id" asp-for="Id" autofocus>
                            </div>
                            <div class="form-group">
                                <label asp-for="Type">Device Type</label>
                                <select class="form-control" asp-for="Type" asp-items="Html.GetEnumSelectList<HomeAutio.Mqtt.GoogleHome.Models.DeviceType>()">
                                    <option selected="selected" value="">Please select</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <a onclick="openDocumentation()" class="btn btn-warning">Device documentation</a>
                            </div>
                            <div class="form-group">
                                <label asp-for="Disabled">
                                    <input asp-for="Disabled" type="checkbox" />
                                    <strong>Disabled</strong>
                                </label>
                            </div>
                            <div class="form-group">
                                <label asp-for="WillReportState">
                                    <input asp-for="WillReportState" type="checkbox" />
                                    <strong>Will Report State</strong>
                                </label>
                            </div>
                            <div class="form-group">
                                <label asp-for="RoomHint">Room Hint</label>
                                <input class="form-control" placeholder="Room Hint" asp-for="RoomHint" autofocus>
                            </div>
                        </fieldset>

                        <div class="panel panel-primary">
                            <div class="panel-heading" data-toggle="collapse" data-target="#NameInfo">Name Information</div>
                            <div id="NameInfo" class="panel-body collapse in">
                                <div class="form-group">
                                    <label asp-for="DefaultNames">Default Names</label>
                                    <input class="form-control" placeholder="Default Names" asp-for="DefaultNames" autofocus disabled>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Name">Name</label>
                                    <input class="form-control" placeholder="Name" asp-for="Name" autofocus>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Nicknames">Nicknames</label>
                                    <input class="form-control" placeholder="Nicknames" asp-for="Nicknames" autofocus disabled>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-primary">
                            <div class="panel-heading" data-toggle="collapse" data-target="#ManufacturerInfo">Manufacturer Information</div>
                            <div id="ManufacturerInfo" class="panel-body collapse">
                                <div class="form-group">
                                    <label asp-for="Manufacturer">Manufacturer</label>
                                    <input class="form-control" placeholder="Manufacturer" asp-for="Manufacturer" autofocus>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Model">Model</label>
                                    <input class="form-control" placeholder="Model" asp-for="Model" autofocus>
                                </div>
                                <div class="form-group">
                                    <label asp-for="HwVersion">Hardware Version</label>
                                    <input class="form-control" placeholder="Hardware Version" asp-for="HwVersion" autofocus>
                                </div>
                                <div class="form-group">
                                    <label asp-for="SwVersion">Software Version</label>
                                    <input class="form-control" placeholder="Software Version" asp-for="SwVersion" autofocus>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="form-group">
                            <button class="btn btn-primary" name="button" value="create">Create</button>
                            <a asp-controller="Devices" asp-action="Index" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/HomeAutio.Mqtt.GoogleHome/Views/Devices/Edit.cshtml
@using HomeAutio.Mqtt.GoogleHome
@model HomeAutio.Mqtt.GoogleHome.ViewModels.DeviceViewModel

@section Scripts {
    <script>
        var openDocumentation = function () {
            var deviceTypeDropDown = document.getElementById("Type");
            var deviceType = deviceTypeDropDown.options[deviceTypeDropDown.selectedIndex].text;

            if (deviceType !== "Please select") {
                window.open('https://developers.google.com/actions/smarthome/guides/' + deviceType.toLowerCase());
            }
        }
    </script>
}

<div class="device-page">
    <div class="page-header">
        <h1>Device: @Model.Id</h1>
    </div>

    <partial name="_ValidationSummary" />

    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Device</h3>
                </div>
                <form method="post">
                    <div class="panel-body">
                        <fieldset>
                            <div class="form-group">
                                <label asp-for="Id">Device Id</label>
                                <input class="form-control" placeholder="Device Id" asp-for="Id" autofocus>
                            </div>
                            <div class="form-group">
                                <label asp-for="Type">Device Type</label>
                                <select class="form-control" asp-for="Type" asp-items="Html.GetEnumSelectList<HomeAutio.Mqtt.GoogleHome.Models.DeviceType>()">
                                    <option selected="selected" value="">Please select</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <a onclick="openDocumentation()" class="btn btn-warning">Device documentation</a>
                            </div>
                            <div class="form-group">
                                <label asp-for="Disabled">
                                    <input asp-for="Disabled" type="checkbox" />
                                    <strong>Disabled</strong>
                                </label>
                            </div>
                            <div class="form-group">
                                <label asp-for="WillReportState">
                                    <input asp-for="WillReportState" type="checkbox" />
                                    <strong>Will Report State</strong>
                                </label>
                            </div>
                            <div class="form-group">
                                <label asp-for="RoomHint">Room Hint</label>
                                <input class="form-control" placeholder="Room Hint" asp-for="RoomHint" autofocus>
                            </div>
                        </fieldset>

                        <div class="panel panel-primary">
                            <div class="panel-heading" data-toggle="collapse" data-target="#NameInfo">Name Information</div>
                            <div id="NameInfo" class="panel-body collapse in">
                                <div class="form-group">
                                    <label asp-for="DefaultNames">Default Names</label>
                                    <input class="form-control" placeholder="Default Names" asp-for="DefaultNames" autofocus disabled>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Name">Name</label>
                                    <input class="form-control" placeholder="Name" asp-for="Name" autofocus>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Nicknames">Nicknames</label>
                                    <input class="form-control" placeholder="Nicknames" asp-for="Nicknames" autofocus disabled>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-primary">
                            <div class="panel-heading" data-toggle="collapse" data-target="#ManufacturerInfo">Manufacturer Information</div>
                            <div id="ManufacturerInfo" class="panel-body collapse">
                                <div class="form-group">
                                    <label asp-for="Manufacturer">Manufacturer</label>
                                    <input class="form-control" placeholder="Manufacturer" asp-for="Manufacturer" autofocus>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Model">Model</label>
                                    <input class="form-control" placeholder="Model" asp-for="Model" autofocus>
                                </div>
                                <div class="form-group">
                                    <label asp-for="HwVersion">Hardware Version</label>
                                    <input class="form-control" placeholder="Hardware Version" asp-for="HwVersion" autofocus>
                                </div>
                                <div class="form-group">
                                    <label asp-for="SwVersion">Software Version</label>
                                    <input class="form-control" placeholder="Software Version" asp-for="SwVersion" autofocus>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="form-group">
                            <button class="btn btn-primary" name="button" value="update">Update</button>
                            <a asp-controller="Devices" asp-action="Index" class="btn btn-default">Cancel</a>
                        </div>
                    </div>
                </form>
                <form method="post" asp-action="Delete" asp-route-deviceId="@Model.Id">
                    <button class="btn btn-danger pull-right" style="position: relative;top: -60px;right:10px" name="button" value="delete" onclick="return confirm('Are you sure you want to delete this item?');">Delete</button>
                </form>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Traits</h3>
                </div>
                <div class="panel-body">
                    <div class="list-group">
                        <a asp-controller="Traits" asp-action="Create" asp-route-deviceId="@Model.Id" class="list-group-item list-group-item-action active">Add Trait</a>
                        @foreach (var trait in Model.Traits)
                        {
                            <a asp-controller="Traits" asp-action="Edit" asp-route-deviceId="@Model.Id" asp-route-traitId="@trait.ToEnumString()" class="list-group-item list-group-item-action">@trait.ToEnumString()</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>