src/HomeAutio.Mqtt.GoogleHome/Controllers/GoogleDeviceController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using HomeAutio.Mqtt.GoogleHome.ActionFilters;
using HomeAutio.Mqtt.GoogleHome.IntentHandlers;
using HomeAutio.Mqtt.GoogleHome.Models;
using HomeAutio.Mqtt.GoogleHome.Models.Request;
using HomeAutio.Mqtt.GoogleHome.Models.Response;
using HomeAutio.Mqtt.GoogleHome.Models.State;
using HomeAutio.Mqtt.GoogleHome.Validation;
using HomeAutio.Mqtt.GoogleHome.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HomeAutio.Mqtt.GoogleHome.Controllers
{
    /// <summary>
    /// Devices controller.
    /// </summary>
    [Authorize]
    public class GoogleDeviceController : Controller
    {
        private readonly IGoogleDeviceRepository _deviceRepository;

        private readonly SyncIntentHandler _syncIntentHandler;

        /// <summary>
        /// Initializes a new instance of the <see cref="GoogleDeviceController"/> class.
        /// </summary>
        /// <param name="deviceRepository">Device repository.</param>
        /// <param name="syncIntentHandler">Sync intent handler.</param>
        public GoogleDeviceController(
            IGoogleDeviceRepository deviceRepository,
            SyncIntentHandler syncIntentHandler)
        {
            _deviceRepository = deviceRepository ?? throw new ArgumentNullException(nameof(deviceRepository));
            _syncIntentHandler = syncIntentHandler ?? throw new ArgumentNullException(nameof(syncIntentHandler));
        }

        /// <summary>
        /// Index.
        /// </summary>
        /// <returns>Response.</returns>
        public IActionResult Index()
        {
            var model = _deviceRepository.GetAll()
                .OrderBy(device => device.Id)
                .ToList();

            return View(model);
        }

        /// <summary>
        /// Gets a SYNC intent response for external validation.
        /// </summary>
        /// <returns>Response.</returns>
        public IActionResult SyncValidate()
        {
            var response = new Response
            {
                RequestId = Guid.NewGuid().ToString(),
                Payload = _syncIntentHandler.Handle(new SyncIntent())
            };

            return Json(response);
        }

        /// <summary>
        /// Gets a device json for external validation.
        /// </summary>
        /// <returns>Response.</returns>
        public IActionResult Json()
        {
            return Json(_deviceRepository.GetAll().ToDictionary(device => device.Id, device => device));
        }

        /// <summary>
        /// Create device.
        /// </summary>
        /// <returns>Response.</returns>
        [ImportModelState]
        public IActionResult Create()
        {
            var model = new DeviceViewModel
            {
                Id = string.Empty,
                Type = DeviceType.Unknown,
                WillReportState = true,
                Name = string.Empty
            };

            return View(model);
        }

        /// <summary>
        /// Create device.
        /// </summary>
        /// <param name="viewModel">View Model.</param>
        /// <returns>Response.</returns>
        [HttpPost]
        [ExportModelState]
        public IActionResult Create(DeviceViewModel viewModel)
        {
            if (_deviceRepository.Contains(viewModel.Id))
            {
                ModelState.AddModelError("Id", "Device Id already exists");
            }

            // Name Info
            var nameInfo = new NameInfo
            {
                Name = viewModel.Name,
                DefaultNames = !string.IsNullOrEmpty(viewModel.DefaultNames)
                    ? viewModel.DefaultNames.Split(',').Select(x => x.Trim()).ToList()
                    : new List<string>(),
                Nicknames = !string.IsNullOrEmpty(viewModel.Nicknames)
                    ? viewModel.Nicknames.Split(',').Select(x => x.Trim()).ToList()
                    : new List<string>()
            };

            // Device Info
            DeviceInfo? deviceInfo = null;
            if (!string.IsNullOrEmpty(viewModel.Manufacturer) ||
                !string.IsNullOrEmpty(viewModel.Model) ||
                !string.IsNullOrEmpty(viewModel.HwVersion) ||
                !string.IsNullOrEmpty(viewModel.SwVersion))
            {
                deviceInfo = new DeviceInfo
                {
                    Manufacturer = !string.IsNullOrEmpty(viewModel.Manufacturer) ? viewModel.Manufacturer : null,
                    Model = !string.IsNullOrEmpty(viewModel.Model) ? viewModel.Model : null,
                    HwVersion = !string.IsNullOrEmpty(viewModel.HwVersion) ? viewModel.HwVersion : null,
                    SwVersion = !string.IsNullOrEmpty(viewModel.SwVersion) ? viewModel.SwVersion : null
                };
            }

            // Set new values
            var device = new Models.State.Device
            {
                Id = viewModel.Id,
                Type = viewModel.Type,
                Disabled = viewModel.Disabled,
                WillReportState = viewModel.WillReportState,
                RoomHint = viewModel.RoomHint,
                Name = nameInfo,
                DeviceInfo = deviceInfo,
                Traits = new List<DeviceTrait>()
            };

            // Final validation
            foreach (var error in DeviceValidator.Validate(device))
            {
                ModelState.AddModelError(string.Empty, error);
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("Create");
            }

            // Save changes
            _deviceRepository.Add(device);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Delete device.
        /// </summary>
        /// <param name="deviceId">Device id.</param>
        /// <returns>Response.</returns>
        [HttpPost]
        public IActionResult Delete([Required] string deviceId)
        {
            if (!_deviceRepository.Contains(deviceId))
            {
                return NotFound();
            }

            // Save changes
            _deviceRepository.Delete(deviceId);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Edit device.
        /// </summary>
        /// <param name="deviceId">Device id.</param>
        /// <returns>Response.</returns>
        [ImportModelState]
        public IActionResult Edit([Required] string deviceId)
        {
            var device = _deviceRepository.FindById(deviceId);
            if (device is null)
            {
                return NotFound();
            }

            var model = new DeviceViewModel
            {
                Id = device.Id,
                Type = device.Type,
                Disabled = device.Disabled,
                WillReportState = device.WillReportState,
                RoomHint = device.RoomHint,
                Name = device.Name.Name,
                DefaultNames = device.Name.DefaultNames is not null
                    ? string.Join(',', device.Name.DefaultNames)
                    : null,
                Nicknames = device.Name.Nicknames is not null
                    ? string.Join(',', device.Name.Nicknames)
                    : null,
                Manufacturer = device.DeviceInfo?.Manufacturer,
                Model = device.DeviceInfo?.Model,
                HwVersion = device.DeviceInfo?.HwVersion,
                SwVersion = device.DeviceInfo?.SwVersion,
                Traits = device.Traits != null
                    ? device.Traits.Select(x => x.Trait).OrderBy(trait => trait)
                    : new List<TraitType>()
            };

            return View(model);
        }

        /// <summary>
        /// Edit device.
        /// </summary>
        /// <param name="deviceId">Device id.</param>
        /// <param name="viewModel">View Model.</param>
        /// <returns>Response.</returns>
        [HttpPost]
        [ExportModelState]
        public IActionResult Edit([Required] string deviceId, DeviceViewModel viewModel)
        {
            var existingDevice = _deviceRepository.FindById(deviceId);
            if (existingDevice is null)
            {
                return NotFound();
            }

            // Name Info
            var nameInfo = new NameInfo
            {
                Name = viewModel.Name,
                DefaultNames = !string.IsNullOrEmpty(viewModel.DefaultNames)
                    ? viewModel.DefaultNames.Split(',').Select(x => x.Trim()).ToList()
                    : new List<string>(),
                Nicknames = !string.IsNullOrEmpty(viewModel.Nicknames)
                    ? viewModel.Nicknames.Split(',').Select(x => x.Trim()).ToList()
                    : new List<string>()
            };

            // Device Info
            DeviceInfo? deviceInfo = null;
            if (!string.IsNullOrEmpty(viewModel.Manufacturer) ||
                !string.IsNullOrEmpty(viewModel.Model) ||
                !string.IsNullOrEmpty(viewModel.HwVersion) ||
                !string.IsNullOrEmpty(viewModel.SwVersion))
            {
                deviceInfo = new DeviceInfo
                {
                    Manufacturer = !string.IsNullOrEmpty(viewModel.Manufacturer) ? viewModel.Manufacturer : null,
                    Model = !string.IsNullOrEmpty(viewModel.Model) ? viewModel.Model : null,
                    HwVersion = !string.IsNullOrEmpty(viewModel.HwVersion) ? viewModel.HwVersion : null,
                    SwVersion = !string.IsNullOrEmpty(viewModel.SwVersion) ? viewModel.SwVersion : null
                };
            }

            var device = new Models.State.Device
            {
                Id = viewModel.Id,
                Type = viewModel.Type,
                Disabled = viewModel.Disabled,
                WillReportState = viewModel.WillReportState,

src/HomeAutio.Mqtt.GoogleHome/Views/GoogleTrait/Create.cshtml
@model HomeAutio.Mqtt.GoogleHome.ViewModels.TraitViewModel

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.8.8/beautify.js"></script>
    <script src="~/lib/codemirror/lib/codemirror.js"></script>
    <script src="~/lib/codemirror/mode/javascript/javascript.js"></script>
    <link rel="stylesheet" href="~/lib/codemirror/lib/codemirror.css" />

    <script src="//rawgithub.com/zaach/jsonlint/79b553fb65c192add9066da64043458981b3972b/lib/jsonlint.js"></script>
    <script src="~/lib/codemirror/addon/lint/lint.js"></script>
    <script src="~/lib/codemirror/addon/lint/json-lint.js"></script>
    <link rel="stylesheet" href="~/lib/codemirror/addon/lint/lint.css" />

    <script src="~/lib/codemirror/addon/fold/foldcode.js"></script>
    <script src="~/lib/codemirror/addon/fold/brace-fold.js"></script>
    <script src="~/lib/codemirror/addon/fold/foldgutter.js"></script>
    <link rel="stylesheet" href="~/lib/codemirror/addon/fold/foldgutter.css" />

    <script src="~/lib/codemirror/addon/edit/closebrackets.js"></script>
    <script src="~/lib/codemirror/addon/edit/matchbrackets.js"></script>

    <script>
        var codemirrorOptions = {
            mode: "application/json",
            lineNumbers: true,
            foldGutter: true,
            gutters: ["CodeMirror-lint-markers", "CodeMirror-linenumbers", "CodeMirror-foldgutter"],
            lint: true,
            matchBrackets: true,
            autoCloseBrackets: true,
        };

        var attributesEditor = CodeMirror.fromTextArea(document.getElementById("Attributes"), codemirrorOptions);
        var commandsEditor = CodeMirror.fromTextArea(document.getElementById("Commands"), codemirrorOptions);
        var stateEditor = CodeMirror.fromTextArea(document.getElementById("State"), codemirrorOptions);

        var attributeExamples = document.getElementById("attributeExamples");
        var commandExamples = document.getElementById("commandExamples");
        var stateExamples = document.getElementById("stateExamples");

        // Create example accordion item
        var getCardCollapseNode = function(parentId, collapseId, comment, example) {
            var cardNode = document.createElement("div");
            cardNode.className = "card";

            // Header
            var cardHeaderNode = document.createElement("div");
            cardHeaderNode.className = "card-header";

            var cardHeaderButtonNode = document.createElement("button");
            cardHeaderButtonNode.className = "btn btn-primary dropdown-toggle";
            cardHeaderButtonNode.style = "width: 100%";
            cardHeaderButtonNode.dataset.bsToggle = "collapse";
            cardHeaderButtonNode.dataset.bsTarget = "#" + collapseId;
            cardHeaderButtonNode.innerHTML = comment;

            cardHeaderNode.appendChild(cardHeaderButtonNode);

            // Collapse
            var cardCollapseNode = document.createElement("div");
            cardCollapseNode.id = collapseId;
            cardCollapseNode.className = "collapse";
            cardCollapseNode.dataset.bsParent = "#" + parentId;
            var bsCardCollapseNode = new bootstrap.Collapse(cardCollapseNode, { toggle: false });

            // Card body
            var cardBodyNode = document.createElement("div");
            cardBodyNode.className = "card-body";

            var preformattedText = document.createElement("pre");
            preformattedText.innerText = example;

            cardBodyNode.appendChild(preformattedText);
            cardCollapseNode.appendChild(cardBodyNode);

            cardNode.appendChild(cardHeaderNode);
            cardNode.appendChild(cardCollapseNode);

            return cardNode;
        }

        // Templates
        var loadTemplate = function () {
            var traitDropDown = document.getElementById("Trait");
            var traitName = traitDropDown.options[traitDropDown.selectedIndex].text;

            if (traitName !== "Please select") {
                // Dispose any existing accordions
                $(attributeExamples.querySelectorAll(".collapse")).collapse("dispose");
                attributeExamples.innerHTML = "";

                $(commandExamples.querySelectorAll(".collapse")).collapse("dispose");
                commandExamples.innerHTML = "";

                $(stateExamples.querySelectorAll(".collapse")).collapse("dispose");
                stateExamples.innerHTML = "";

                // Make call to get examples for traitName
                $.get("Examples?traitId=" + traitName, function (examples) {
                    // Add new accordions
                    for (var i in examples.attributeExamples) {
                        var parentId = "attributeExamples";
                        var childId = "attributeExample" + i;
                        var comment = examples.attributeExamples[i].comment;
                        var example = examples.attributeExamples[i].example;

                        attributeExamples.appendChild(getCardCollapseNode(parentId, childId, comment, example));
                    }

                    // Add new accordions
                    for (var i in examples.commandExamples) {
                        var parentId = "commandExamples";
                        var childId = "commandExample" + i;
                        var comment = examples.commandExamples[i].comment;
                        var example = examples.commandExamples[i].example;

                        commandExamples.appendChild(getCardCollapseNode(parentId, childId, comment, example));
                    }

                    // Add new accordions
                    for (var i in examples.stateExamples) {
                        var parentId = "stateExamples";
                        var childId = "stateExample" + i;
                        var comment = examples.stateExamples[i].comment;
                        var example = examples.stateExamples[i].example;

                        stateExamples.appendChild(getCardCollapseNode(parentId, childId, comment, example));
                    }
                });
            }
        };

        var openDocumentation = function () {
            var traitDropDown = document.getElementById("Trait");
            var traitName = traitDropDown.options[traitDropDown.selectedIndex].text;

            if (traitName !== "Please select") {
                window.open('https://developers.google.com/actions/smarthome/traits/' + traitName.toLowerCase());
            }
        }
        
        var challengePinHideShow = function () {
            if ($("#ChallengeType").val() == '2') {
                $('#challengePin-form-group').show();
            } else {
                $('#challengePin-form-group').hide();
            }
        };

        $(function () {
            loadTemplate();
            challengePinHideShow();
            $('#ChallengeType').change(challengePinHideShow);
        });
    </script>

    <style>
        .CodeMirror {
            border: 1px solid #ccc;
            border-radius: 4px;
            box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
        }
    </style>
}

<div class="trait-page">
    <partial name="_ValidationSummary" />

    <div class="row">
        <div class="col-sm-6 mt-3">
            <div class="card">
                <div class="card-header">
                    <h2>Trait Information</h2>
                </div>
                <form id="createForm" method="post"></form>
                <div class="card-body">
                    <fieldset>
                        <div class="mb-3">
                            <label class="form-label" asp-for="Trait">Trait</label>
                            <select form="createForm" class="form-select" asp-for="Trait" asp-items="@(Html.GetEnumSelectList<HomeAutio.Mqtt.GoogleHome.Models.TraitType>().Where(x => x.Text != "Unknown"))" onchange="loadTemplate()">
                                <option selected="selected" value="">Please select</option>
                            </select>
                        </div>

                        <div class="mb-3">
                            <label class="form-label" asp-for="ChallengeType">Challenge Type</label>
                            <select form="createForm" class="form-select" asp-for="ChallengeType" asp-items="@Html.GetEnumSelectList<HomeAutio.Mqtt.GoogleHome.Models.State.Challenges.ChallengeType>()"></select>
                        </div>

                        <div class="mb-3" id="challengePin-form-group">
                            <label class="form-label" asp-for="ChallengePin">Challenge Pin</label>
                            <input form="createForm" class="form-control" placeholder="Challenge Pin" asp-for="ChallengePin">
                        </div>

                        <div class="mb-3">
                            <label class="form-label" asp-for="Attributes">Attributes</label>
                            <textarea form="createForm" class="form-control" asp-for="Attributes"></textarea>
                        </div>

                        <div class="mb-3">
                            <label class="form-label" asp-for="Commands">Commands</label>
                            <textarea form="createForm" class="form-control" asp-for="Commands"></textarea>
                        </div>

                        <div class="mb-3">
                            <label class="form-label" asp-for="State">State</label>
                            <textarea form="createForm" class="form-control" asp-for="State"></textarea>
                        </div>
                    </fieldset>
                </div>
                <div class="card-footer">
                    <div class="mb-0">
                        <button form="createForm" class="btn btn-primary" name="button" value="update">Create</button>
                        <a asp-controller="GoogleDevice" asp-action="Edit" asp-route-deviceId="@(Context.Request.Query["deviceId"])" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 mt-3">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h2>Examples</h2>
                    <button onclick="openDocumentation()" class="btn btn-warning">Trait documentation</button>
                </div>
                <div class="card-body">
                    <h6>Attribute Examples</h6>
                    <div id="attributeExamples"></div>

                    <h6>Command Examples</h6>
                    <div id="commandExamples"></div>

                    <h6>State Examples</h6>
                    <div id="stateExamples"></div>
                </div>
            </div>
        </div>
    </div>
</div>